// <auto-generated />
namespace ABLeasing.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class StaffNullDateHired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StaffNullDateHired));
        
        string IMigrationMetadata.Id
        {
            get { return "201311201513058_StaffNullDateHired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
