// <auto-generated />
namespace ABLeasing.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class suckgay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(suckgay));
        
        string IMigrationMetadata.Id
        {
            get { return "201311141042578_suckgay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
