// <auto-generated />
namespace ABLeasing.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class IdChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201312191347325_IdChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
