// <auto-generated />
namespace ABLeasing.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ClientModelUpdates1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClientModelUpdates1));
        
        string IMigrationMetadata.Id
        {
            get { return "201311210315449_ClientModelUpdates1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
