// <auto-generated />
namespace ABLeasing.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class clients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clients));
        
        string IMigrationMetadata.Id
        {
            get { return "201311110145108_clients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
