// <auto-generated />
namespace ABLeasing.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class nullableagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullableagain));
        
        string IMigrationMetadata.Id
        {
            get { return "201311141058478_nullableagain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
