// <auto-generated />
namespace ABLeasing.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FixingAnotherError : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixingAnotherError));
        
        string IMigrationMetadata.Id
        {
            get { return "201311201511584_FixingAnotherError"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
